version: 2.1

jobs:
  terraform-deploy:
    docker:
      - image: hashicorp/terraform:latest  

    steps:
      - checkout  

      - run:
          name: "Set AWS Credentials"
          command: |
            export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
            export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
            export AWS_REGION="us-west-2"

      - run:
          name: "Terraform Init"
          command: terraform init

      - run:
          name: "Terraform Plan"
          command: terraform plan -out=tfplan

      - run:
          name: "Terraform Apply"
          command: terraform apply -auto-approve tfplan

workflows:
  terraform-workflow:
    jobs:
      - terraform-deploy
